### PR TITLE
Add translation into Spanish

### PR DESCRIPTION
**Pull request by nvdaes**
Especial characters are perfectly presented and Windows notifies when download is finished playing the bell sound.

### CODE REVIEW

**Comment by nvdaes** [comment]
Thanks, should this be compresed in a zip file, or perhaps in a self extracting exe file?

**Comment by ABuffEr** [comment]
My first pr/contribution, Github is happy too :D Thanks @nvdaes!

**Comment by ABuffEr** [comment]
For zip, well... you prefer different archives for es and international version, I suppose. I can see.

**Comment by nvdaes** [comment]
Oh, I'm happy too 😏

**Comment by nvdaes** [comment]
ABuffErcommented 

> you prefer different archives for es and international version, I suppose. 

I suppose it's the best solution, to add other possible translations on your repo, so that translators and you are connected for future updates, if any.
I will wait you release a zip or exe file to post this on the nvdaes.github.io website, and I will inform now about this merged PR on the mailing list.

**Comment by ABuffEr** [comment]
Hi,
I released version 1.0, including language-based zip under Releases section and directly in repo structure. The latter could allow more easy linking in other external site, maybe...

**Comment by nvdaes** [comment]
Thanks, I will post this on the website, probably tomorrow.

**Comment by nvdaes** [comment]
I've translated the readme (with the direct link to the spanish zip), in a section of this page:
https://nvdaes.github.io/ayuda

Thanks a lot

**Comment by ABuffEr** [comment]
Hi @nvdaes ,
I released version 2.0 in English some days ago. Because of I introduced no new messages, I released now also Spanish version, integrating changed/new code.
The main news is the ability to download from virtually any branch present in snapshots page.
I'd happy if you'll check my Spanish version and announce it in your community :)

**Comment by nvdaes** [comment]
Thanks! I will spread this arround the world :), on mailing lists and Twitter (my user name is norrumar on this social network, not too much used by me), but this is great and here is your post on a Spanish NVDA's website:

https://nvdaes.github.io/nvdaSnapshotDownloader-2

See you soon, I have updated instructions mentioning rc and all available branches according to readme, also at
https://nvdaes.github.io/ayuda

I have linked to the direct zip archive in Spanish for 2.0.

**Pull request merged**
