### PR TITLE
Update spanish translation

### PR DESCRIPTION
**Pull request by nvdaes**
I've tested this on Windows 11, before and after updating spanish translation, in case Windows 11 should be mentioned in the readme.

### CODE REVIEW

**Comment by nvdaes** [comment]
cc: ABuffEr

**Comment by ABuffEr** [comment]
Hi @nvdaes . Good suggestion, thanks! 🎉

**Comment by nvdaes** [comment]
Thanks @ABuffEr.
When you public a release containing these changes, I'll update this  [post about the old NVDASnapshotDownloader](https://nvdaes.github.io/nvdaSnapshotDownloader-2).
🙌

**Comment by AlbumBlog** [comment]
Hi @nvdaes ,
just published 4.1, including new es translation!
(I cited you in release changes, but don't know if GitHub notify it in that context)

**Comment by ABuffEr** [comment]
Hi @nvdaes ,
just published 4.1, including new es translation!
(I cited you in release changes, but don't know if GitHub notify it in that context)

**Comment by nvdaes** [comment]
Hi @ABuffEr , thanks for this update and also for keeping me informed! I received two notifications on GitHub Mobile.
I updated the mentioned post and now I'll share it on my spanish mailing list for NVDA, where other translators of NVDAVersionDownloader are subscribed too.
I've updated the post including Giscus, used in newer publications on the NVDA spanish website associated with the mailing list. In case you don't know this app:

https://giscus.app

**Pull request merged**
